name: Check Coding Standards

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  check-coding-standards:

    runs-on: ubuntu-24.04

    env:
      PHP_CS_FIXER_IGNORE_ENV: 1

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with no coverage driver
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run coding style checks
        run: composer run-script check-style

      - name: Run static analysis
        run: composer run-script stan -- --error-format=github
